### ISSUE TITLE
Global option for disabling autocomplete?

### ISSUE THREAD

**Issue by cafreeman** [robinbentley/vscode-sass-indented#13]
I was wondering if there was a global config variable for turning off autocomplete with this addon? I only need it for the syntax highlighting and the autocomplete is causing some serious performance issues.

Is there a way to disable autocomplete without needing to put `.sassconfig` file in each project?

**Comment by robinbentley** [comment]
Hi Chris, 

There is nothing available at the moment but I can look at adding it. 

Could you also give me a bit more information on the performance issues you are having. Platform, version and what is actually going wrong.

Thanks

**Comment by cafreeman** [comment]
Hey!

I'm using:

VSCode v1.7.2
Sass-Indented v1.2.1
OS X El Capitan
15" MBP

Basically, I have some projects with highly modular sass (lots and lots of folders), and the add-on seems to be trying to watch all of the files constantly for autocomplete. As a result, every time I edit a stylesheet and hit `.` or `:` or anything else that might trigger autocomplete, the entire editor freezes for a few seconds and then staggers back into operation.

I was able to solve this problem completely by adding a `sassconfig.json` file that looks like this:
```json
{
  "exclude": [
    "*"
  ]
}
```

**Comment by robinbentley** [comment]
Great, thanks for the details, I'll look into it. The add on polls files for anything $ to allow for the completion of variables across a project, I personally haven't noticed any issues but my projects are usually only 30-40 individual files.

I'll put together a larger project and see what the deal is with the hangs. I'll also add a config option that can live in the user settings to disable autocomplete all together because that's a nice idea in its self.

**Comment by robinbentley** [comment]
@cafreeman Hey Chris, 

I have pushed an update to the extension gallery that has removed the global autocompletion for the time being. It's causing a lot of performance issues so it's better just gone whilst these can be resolved. Once I have had a chance to get it back in there cleanly I'll make sure there is a way that it can be disabled from config rather than having to use a sassconfig per project.

I am 99% sure that the issues you faced were because the extension was trying to scan over so many files to find the completions so this should resolve that. Could you update and let me know if it's any better for you please.

Cheers

**Comment by Ventajou** [comment]
@robinbentley I think the TypeScript Hero extension uses a cache of the TypeScript exports in the project for intellisense, and that cache is updated on file save. There's a status bar button to trigger reindexing the files. Maybe that's a technique you could use in your plugin? 

I've been dreaming of project level intellisense on SASS variables for a long time, if you make it happen I'd be eternally grateful!

**Comment by robinbentley** [comment]
@Ventajou Thanks, André. That sounds like a great idea. I'll look at how they have that implemented.

**Comment by mattez** [comment]
@Ventajou this "project level intellisense" is already done for LESS. 
[Less IntelliSense](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-less) Less IntelliSense (Variables and Mixins) for all files in the workspace. And It is really super most useful!!

I made a wish for this feature in this issue #45

**Comment by robinbentley** [comment]
Going to close this off for now since it's almost 2 years old and not relevant to the current state of the project. The autocompletion is planned for a `2.0` early next year and this will be factored in for that.
