### ISSUE TITLE
Mixins colors in vscode 1.9.0

### ISSUE THREAD

**Issue by lgrano** [robinbentley/vscode-sass-indented#16]
Hello, after my vscode upgraded to 1.9.0  the operators before mixin names changed the color to expression operators color.

Example: `+mixin-name`  now  the + operator has the same color of a expression `width: 15 + 25em` 
Can somebody else reproduce this?

Thank you for the extension, wouldn't be using vscode without it!

**Comment by robinbentley** [comment]
@granoz Thanks for the report, Luiz. I can recreate what you have described.

I've had a quick look through the patch notes there isn't that jumps out as a cause. I'll have a better look when I'm home from work.

Glad it helps you!

**Comment by robinbentley** [comment]
@granoz I've had closer look, this is a (non)issue with color themes.

With the theme I use normally [Voronianski Oceanic Next](https://marketplace.visualstudio.com/items?itemName=Alexander.theme-sublime-oceanicnext) you can see the mixin `+` is highlighted correctly, however, the built in Monokai shows the issue you described.

![oceanic](https://cloud.githubusercontent.com/assets/2156395/22618324/733a1da4-ead1-11e6-93e5-b2417aa482f0.jpg)

![monokai](https://cloud.githubusercontent.com/assets/2156395/22618326/7890a19c-ead1-11e6-9a47-7fb514848ed9.jpg)

The problem is that some themes just don't account for the full range of usage in the syntax, some themes see the `+` and automatically presume it's an operator without checking any sort of scope so they color it as such and move on.

what I don't know is why it's only become apparent since you updated to 1.9.0, the patch notes don't show anything that could have had an effect.

Which color theme do you use and are you on mac/windows/linux? I can try with your settings.

**Comment by lgrano** [comment]
You're right, i tested a few themes, its a theme based issue, my main theme is [1337](https://marketplace.visualstudio.com/items?itemName=ms-vscode.Theme-1337) and i'm on windows.  Some themes change the operator color when followed by a char or a string, some don't, but the color used to be the same as "string" and now its a "symbol" color (like @ or !).

**Comment by robinbentley** [comment]
[https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations#_finally-whats-new-in-vs-code-19](https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations#_finally-whats-new-in-vs-code-19)

This will be why, the editor got some nice improvements to the way syntax highlighting works. I'm not going to change anything to account for this because technically it's correctly more now than before. It's up to themes to make sure that they have definitions for everything.
