### ISSUE TITLE
Delete snippets of CSS properties from plugin

### ISSUE THREAD

**Issue by mrmlnc** [robinbentley/vscode-sass-indented#2]
Hello, @robinbentley,

Starting with version 1.3 editor supports Emmet for Sass. It might be worth to remove snippets of CSS properties from plugin to not clog the autocompletion? That is, keep only snippets for language constructs.

For example:

![2016-07-25_18-55-40](https://cloud.githubusercontent.com/assets/7034281/17107790/68fc86ea-5299-11e6-8ae3-4a14c64a1085.gif)

**Comment by robinbentley** [comment]
Thanks for the heads up on the Emmet change, I've been meaning to have a full review as there are a few more property changes/removals I need to make.

I'll look into it shortly

**Comment by 256k** [comment]
im asking this here because i dont want to open a new issue since this seems somewhat related. i just installed vscode and installed the indented sass, but i find that the "atucompletion" is horrendeous... it's not contextual at all... it just opens up a list of words that would possibly fit what im writing.

I'm seeking to have a similar behaviour as i have on atom. as this is the only hurdle keeping me from really using vscode primarily.

i'm not a fan of emmet personally and i dont want to memorize shortcuts and use tabs i much prefer writing my tags myself but have a autocomplete menu drop of the options for example if i write display: id like to have the display options pop up.
is there another package exptention that i am missing? or is this something missing from this exptention?

**Comment by mrmlnc** [comment]
@256k, If I understand correctly, you're talking about ToolTips property values. To do this, the extension author must write autocomplete provider using editor API's. For example: https://github.com/d4rkr00t/language-stylus/blob/master/src/completion-item-provider.ts

**Comment by robinbentley** [comment]
Hi @256k, 

The text is showing available snippets that could be used, it's not not meant to be autocomplete.

This was the best way to accommodate Emmet users at the time because it wasn't available for use in the indented syntax. It's literally the only reason I created it. As @mrmlnc has pointed out Emmet is now available so these snippets will be removed from the extension shortly to stop any further confusion.

I'll look into what's involved regarding adding autocomplete but I don't actually use the editor in my day to day so there will be no ETA on this being added just yet.

Feel free to fork this repo and add to it or even create a brand new extension that suits your needs better

**Comment by robinbentley** [comment]
Thanks for that @mrmlnc I'll have a look at it later this evening

**Comment by mrmlnc** [comment]
@robinbentley, I'll try to do autocomplete provider, but can't promise anything.

**Comment by 256k** [comment]
@robinbentley thanks for the offer to clone and adjust, but i wouldn't even know where to start on writing my own extension. perhaps later down the line i'll make time to learn how.

@mrmlnc yeah i think that's what i'm talking about.... that link you shared though doesn't really explain much to me. but i appreciate it i'll try to delve deeper into this extensions world.

edit: @mrmlnc i get it now. :)

**Comment by mrmlnc** [comment]
@256k,

Maybe you provide any video/gif of your ideas? As I understand, you talk about this:

![2016-08-27_22-48-47](https://cloud.githubusercontent.com/assets/7034281/18029718/742e0dee-6ca8-11e6-83e6-e1f4fa10d58b.gif)

**Comment by 256k** [comment]
@mrmlnc pretty much.
i'll try to grab the functionality in a gif from my atom editor to show.

**Comment by 256k** [comment]
![sassdemo](https://cloud.githubusercontent.com/assets/16099871/18030214/48ee3e6e-6c7c-11e6-8143-7d1afb5dd3cb.gif)
@mrmlnc here it is. 
i've tried a lot of different text editors and nothing had as good a autocomplete/suggestion box as atom.

**Comment by robinbentley** [comment]
@mrmlnc @256k Got it working, just need to have a tidy up, test and then I can push it to the gallery. Will be available in a couple of days.

Ignore the sloppy typing, it's late

![gifrecord_2016-08-28_021554](https://cloud.githubusercontent.com/assets/2156395/18031020/96310154-6cc5-11e6-8d0f-1cc24ae37d6d.gif)

**Comment by 256k** [comment]
Awesome! That's looking a lot better :)

**Comment by robinbentley** [comment]
The updates are all available on the gallery now. Let me know how you get on with it.
