### ISSUE TITLE
No sugestion for variable imported from other files

### ISSUE THREAD

**Issue by AlexTeixeira** [robinbentley/vscode-sass-indented#21]
Hello,

I'm currently storing all my "core" variables inside a common file.
When I try to acceed it from another file suggestion does not work.

Exemple : 

**variables.scss**

`$white-color: #fff;
`

**core.scss**

```
p{
 color: $white-color; //no suggestion here
}

```

**Comment by robinbentley** [comment]
Hi @AlexTeixeira, 

Sorry for the delayed response, have been busy.

At the moment you won't get suggestions across files, this was implemented in a previous version but had to be disabled because of performance issues. Once these have been worked out it will be re-implemented, I just haven't had a decent opportunity to look at it yet.


EDIT:

I just noticed you're using `.scss`, this extension only contributes to `.sass` (the indented syntax) if you want better `.scss` support I recommend the [SCSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss) extension
