### ISSUE TITLE
About .scss support

### ISSUE THREAD

**Issue by kazzkiq** [robinbentley/vscode-sass-indented#26]
Is there any reason as to why the project stopped with `.scss` support?

I remember using it sometime ago and the autocomplete was flawless, worked like a charm. But it seems that since `v1.3.1` the extension dropped support for SCSS without further details. Which is a shame for those who used it with this Sass format.

Since this is by far the best SASS/SCSS plugin I came across in VS Code, is there any chance to start supporting `.scss` again?

**Comment by robinbentley** [comment]
Hi Claudio, 

Thank you for your comments!

The `.scss` support, that was actually a (happy?) accident caused by scanning `.scss` files for variables to add to the autocomplete. This extension was only ever intended to add support for the indented syntax (`.sass`) as VSCode doesn't support this out of the box. The unintentional "support" for `.scss` was dropped when the autocomplete was disabled.

The autocomplete had to be disabled as it was causing major performance issues for projects that had a large number of files and clashing with/overriding the built in support. I do have plans to re-implement it but with starting a new position and renovating a home I just haven't had any decent time to sit and get on with it. I need to look at the current state of the VSCode extension APIs and see if bringing a 2.0 would be better than building on top of the existing extension, unfortunately,  I have no ETA on this at the moment but when I do I will look at the best options for allowing the functionality to be used in `.scss` files again without causing problems with the existing support.

Have you tried the [SCSS Intellisense](https://github.com/mrmlnc/vscode-scss) extension, perhaps this could help you for the time being? I don't use `.scss` personally so I'm not sure how it's features work.

I'm sorry I can't be more specific at the moment, if you star or watch the repo hopefully you'll see some updates in the near future.

**Comment by kazzkiq** [comment]
The SCSS Intellisense plugin seems to do the trick for now. Thanks for your support, and great plugin! 😃
