### ISSUE TITLE
compile .sass files into .css

### ISSUE THREAD

**Issue by frani00** [robinbentley/vscode-sass-indented#27]
I installed this extension, I think is working correctly, but when I have to compile the files only works with scss syntax and not the indented syntax.

As i am new with sass I wanted to know, how to use this extension correctly , if I need to install other things, or if I need to change the settings from some files.

**Comment by robinbentley** [comment]
Hi, 

This extension only adds support for syntax highlighting and snippets for `.sass` files because VSCode doesn't support them by default, it doesn't have anything to do with the compilation at all.

To compile the files you have to use `sass` on the command line or a build tool such as gulp, grunt or webpack, but could differ depending on what you're working with.

If you give me a some more info, a little example of your project setup and how you are trying to compile I will be happy to help you get going with it.

**Comment by robinbentley** [comment]
I'm going to close this because of the lack of response. I will re-open if/when this is supplied.
