### ISSUE TITLE
emmet does not work in this extension ...

### ISSUE THREAD

**Issue by OrionPro** [robinbentley/vscode-sass-indented#44]
here did prt sc http://prntscr.com/j5gnu3 (it is written no offers)
Ps If you open the extension of the stylus or scss (for example), the emmet works...

**Comment by robinbentley** [comment]
Hi Alexandr,

Thanks for the screenshot, I'm sorry I don't understand cyrillic so I don't know if I am missing something from the things that are highlighted? Emmet is working without issue for me. Could you give me a bit more information please

![emmet](https://user-images.githubusercontent.com/2156395/38777301-9d213fe4-409d-11e8-88a3-355868df1084.gif)


**---- From Google Translate ----**
Спасибо за скриншот, извините, я не понимаю кириллицу, поэтому я не знаю, не хватает ли я чего-то из вещей, которые выделены? Эммет работает без проблем для меня. Не могли бы вы дать мне немного больше информации, пожалуйста
**---- End Google Translate ----**

**Comment by OrionPro** [comment]
Hi Robin , I checked in more detail and found such a bug ... in one .sass file at the beginning of the code emmet does not work, and then emmet it starts working. I do not even know what it's all about. ( From Google Translate :)) PS in Cyrillic there it is written that:  "no offers"

**Comment by OrionPro** [comment]
Robin, Most likely this is some kind of bug ... in other files with the extension sass, I checked and everything works there. Thanks for the help.

**Comment by robinbentley** [comment]
No problem, sorry we haven't got anywhere with it! If you think it might be a bug with Emmet then it might be worth asking on the main VSCode repo, since this extension uses the built in Emmet. 

I'm going to close this for now but if you have any other problems let me know. 👍 

   
   

**---- From Google Translate ----**
Нет проблем, извините, у нас нигде нет! Если вы считаете, что это может быть ошибка с Emmet, возможно, стоит обратиться к основному репозиторию VSCode, поскольку это расширение использует встроенный Emmet.

Я собираюсь закрыть это сейчас, но если у вас есть другие проблемы, дайте мне знать. 👍 
**---- End Google Translate ----**
