### ISSUE TITLE
IntelliSense (autocomplete) variables and mixins from other .sass files (not only from files via @import)

### ISSUE THREAD

**Issue by mattez** [robinbentley/vscode-sass-indented#45]
When I migrated to Bootstrap 4, I have to also migrate from LESS to SASS.
I was used to use this VSCode plugin [Less IntelliSense](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-less).
It can **autocomplete (IntelliSense) variables and mixins for all files in the workspace**. This plugin autocomplete variables only from files already @imported. 

I'm really missing support for this in this SASS plugin.  It is most favorite VSCODE plugin for SASS and it still do not support autocomplete/inteliSense variables from different .sass files.
It is pretty useless when you work with SASS file structure like it is in Bootstrap:
- one file with variables
- some partial files with custom styles (where I use variables)
- last file with only @imports of partial SASS files which pack all together.

Please add support for this to this plugin. Thank you.

**Comment by mattez** [comment]
I just find out that @mrmlnc made module also for Sass (**SCSS** syntax only):
On GitHub: https://github.com/mrmlnc/vscode-scss
On VSCode Marketplace: https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-scss
For now I recommend use last (unpublished jet) version 7.0.0:
https://github.com/mrmlnc/vscode-scss/issues/49#issuecomment-308559385

**Comment by robinbentley** [comment]
Hi @mattez, 

Re-enabling project wide auto completion is on the todo list, however, I don't have an ETA for it as I don't have the time available for feature development right now. There was performance issues with large projects in the first iteration.

Although if `vscode-scss` is working for you then that would indicate you are working with `.scss` files? Have you switched your project to `.scss` from `.sass` files or did you move from `.less` straight to `.scss`?.

I ask because if you are working with `.scss` files then this extension isn't the right one for you anyway, it only adds support for the indented syntax (`.sass`) and isn't enabled for `.scss`. Any support prior to you installing `vscode-scss` would have been coming from the built in VSCode scss.

**Comment by mattez** [comment]
Hi @robinbentley,
thanks for you reply. I'm new in this SASS/SCSS world. You are right.
We just migrate form `.less` (Bootstrap 3) to `.scss` (Bootstrap 4).
Whoops..

**Comment by robinbentley** [comment]
@mattez No Problem! It happens all the time because of the two syntax versions under the same language name.

I'm going to close this for now but if you do ever try the indented syntax and need any help feel free to give me a shout.

**Comment by davidponces** [comment]
@robinbentley Any news on SASS autocomplete that you mentioned was in the works? Or if by any chance you know any other way to do it? Thanks

**Comment by robinbentley** [comment]
Hi @davidponces,

I've had no time to work on anything substantial for the extension for a while, and between the day job and a new baby it's unlikely I will for the foreseeable future. I'm always open for discussion and review if anyone wants to have a crack at a PR for it though. 

Unfortunately, other than switching to the curly syntax, I don't know of another way to get this going. You can watch the repo and you'll get notified of any updates but I don't know when they will be.
