### ISSUE TITLE
Enter messes indentation

### ISSUE THREAD

**Issue by alivefromsomewhere** [robinbentley/vscode-sass-indented#54]
I made this video https://streamable.com/yt2is and it may be confusing so I'm gonna explain
if you press enter on the an empty line or a non indented line, it gets indented. I like to put an empty line between selectors with properties but I always have to delete indentation. ofc the first new line will be indented but why the second that's coming after an empty line?
also if you press backspace the line goes up and gets indented. I don't know why.
the first issue can avoided by pressing ctrl+shift+enter instead of enter but that's a bit heavy and meant to be used if you are in the middle of the line not the start of it.

**Comment by alivefromsomewhere** [comment]
![image](https://user-images.githubusercontent.com/36825810/50298827-fb955d00-0477-11e9-8cda-8e0ff4c8c909.png)
disable auto indent

**Comment by robinbentley** [comment]
@alivefromsomewhere sorry I'm just getting to this now. It's a busy time of the year! 

You shouldn't have to disable auto indent across the editor because of one extension misbehaving. I've been meaning to implement #50 which would help you and off the top of my head I have a quick solution to the problem you're having without having to disable at all. I'll try it and aim to publish this evening.

The issue is, without having a proper language server, I had to use the built in `onEnterRules` to add basic auto indentation. This means it's unable to check what's on the previous or next lines to make an informed decision about if it should indent or not. I've never been happy with it and if I'm honest never even thought about it until people started to request it.

I'm going to re-open this because it's a valid issue. Thanks for the report

**Comment by robinbentley** [comment]
Added the config option to disable auto indentation for the extension as a start. I need a bit more time to fix the regex for indentation rules to really address this issue.
