### ISSUE TITLE
Conflicts with sass-lint extension?

### ISSUE THREAD

**Issue by glen-84** [robinbentley/vscode-sass-indented#9]
Hi Robin,

It seems like your extension is conflicting with [mine](https://marketplace.visualstudio.com/items?itemName=glen-84.sass-lint):

**With your extension disabled:**

![sass-1](https://cloud.githubusercontent.com/assets/261509/20033059/b30bda94-a3a0-11e6-9889-9a9bf7fa72b2.png)

**With your extension enabled:**

![sass-2](https://cloud.githubusercontent.com/assets/261509/20033063/b796076a-a3a0-11e6-90d8-e1bb86047ee4.png)

I've also had a number of VS Code crashes lately, which could be related.

OS: Windows 10
VS Code: 1.7.1

Any ideas?

**Comment by robinbentley** [comment]
Hi Glen, Thanks for the heads up. Is there anything being output to 'Problems' when both extensions are running? Just did a quick check on my linux and macOS with no issues, I'll get onto my windows shortly and see if I find anything.

Judging by some of the issues on the VSCode repo 1.7.1 seems to have caused quite a few problems with a lot of extensions for windows users so it could be that I'm pulling in something from the core that's causing mine to have an issue that's being chained to yours.

I'll see what I can do

**Comment by glen-84** [comment]
Nothing in `Problems` or extension output, but I do see this in the developer console:

```
Overwriting extension <<.scss>> to now point to mime <<text/x-sass>>
```

**Comment by robinbentley** [comment]
HI Glen, 

Just did a fresh install of both extensions from the marketplace and tried them out on my windows. The only result was sass-lint crashing on launch with sass-indented disabled and even with it completely removed.

I get the info bar across the top and the output panel shows the following

```
[Info  - 23:02:53] Connection to server got closed. Server will restart.
[Info  - 23:02:54] Connection to server got closed. Server will restart.
[Info  - 23:02:54] Connection to server got closed. Server will restart.
[Info  - 23:02:55] Connection to server got closed. Server will restart.
[Error - 23:02:56] Connection to server got closed. Server will not be restarted.
```

sass-lint is installed and working via cmd

I'm not a windows user so if this is something common and I am setup wrong let me know and I will go over it again.

![sass-test](https://cloud.githubusercontent.com/assets/2156395/20034152/778c2fd0-a3ac-11e6-819d-62806aa5a80f.PNG)

**Comment by glen-84** [comment]
Which version of sass-lint are you using?

**Comment by robinbentley** [comment]
0.0.3, it's in the screenshot

**Comment by glen-84** [comment]
I was referring to [sass-lint](https://www.npmjs.com/package/sass-lint), not the extension. =)

**Comment by robinbentley** [comment]
haha sorry, it's 1.9.1

**Comment by glen-84** [comment]
I just played around with `1.9.1`, and I'm unable to reproduce that error. 😞

Are you using the built-in sass-lint configuration?

**Comment by robinbentley** [comment]
Yep that was with the built in config. Just a straight install of both extensions from the marketplace and a fresh install of sass-lint `1.9.1` globally. I think it might have been something to do with me setting it up though because I have just tried again and both extensions are enabled and working completely.

![sass-lint-test-scss](https://cloud.githubusercontent.com/assets/2156395/20039897/9e318a5c-a444-11e6-8f67-bddb59ad1d1e.jpg)
![sass-lint-test-sass](https://cloud.githubusercontent.com/assets/2156395/20039898/9e31f320-a444-11e6-9226-7c710dd5590b.jpg)

So, with that I am getting no crashes or errors across all 3 platforms with both extensions on and working as intended.

Were you using a different version of sass-lint? I could install that version and see if anything happens. Perhaps it's related to the node version? I have `7.0.0` installed on the windows machine.

Quick question, in your initial screenshots the one with mine disabled shows the built in tooltip "Color of an elements text" but doesn't show any of the sass-lint extension tooltips? Why is this? Was the sass-lint extension running at the time because if I put `a{color:red}` into an `.scss` file I see

![scss-linting](https://cloud.githubusercontent.com/assets/2156395/20040033/b78f2cfe-a447-11e6-8cab-2c6495393e40.jpg)

**Comment by robinbentley** [comment]
@glen-84 Are you still seeing issues?

**Comment by glen-84** [comment]
> Were you using a different version of sass-lint?

I was using `1.8.2`, but I installed `1.9.1` to test as well (same issue).

> Perhaps it's related to the node version?

I'm using `6.9.1`.

> ... doesn't show any of the sass-lint extension tooltips? Why is this?

I was only hovering over the word `color`, to show that `Loading...` message.

> Are you still seeing issues?

The issue is still present when I re-enable your extension.

Maybe you need a larger test file or project? I'm really not sure what the difference is. 😕

**Comment by robinbentley** [comment]
hmmm odd,  could you perhaps create a small repo/attach files that causes the issue that I could clone and try with? I have been been doing some of my work on windows this week and everything still looks to be working fine here.

**Comment by glen-84** [comment]
Hey Robin,

I apologize for the delayed reply. I've been able to narrow this down a bit, and I've attached a folder that should allow you to reproduce the issue (on Windows, at least).

Strangely enough, if you disable *either* of our extensions, the issue disappears.

There must be a file or folder under `public/jspm_packages` that is causing the problem. If you want, I can try to narrow it down further.

[test-project.zip](https://github.com/robinbentley/vscode-sass-indented/files/658955/test-project.zip)

**Comment by robinbentley** [comment]
Thanks for that Glen! I'll have a look at it in the coming week and see if I can pick up on anything.

**Comment by robinbentley** [comment]
@glen-84 I think I've worked out what was going on from that example.

When the extension is loaded it polls for files in the workspace that may contain variables to add them into the autocomplete, as it scans it looks like they are loaded and the built in `scss` validation is being triggered. On windows when you have a large number of files like in the `public` dir of the example it basically chokes the editor, fails silently and then your linting is never actually loaded, on Linux and macOS for some reason it doesn't fail and manages to get through the initial load spam which is why I think I've never noticed it day to day.

Due to having other reports of performance issues after that update I have rolled it back to the basic functionality for the time being because I'm not going to have a chance to work on it and I don't want to leave people dealing with these issues and I really don't want people to start opening issues with you when as far as I can see this issue isn't caused by anything at your end.

I've already pushed the update to the gallery so once you do the update can you confirm it's resolved and we can get this closed!

**Comment by glen-84** [comment]
Confirmed!

Thanks a lot for looking into this.

**Comment by robinbentley** [comment]
@glen-84 No problem and thank you for helping me get to the bottom of it. Apologies for any issues you've had to deal with because of it
